### ISSUE TITLE
iOS Support?

### ISSUE THREAD

**Issue by stevenp** [elegantchaos/DictionaryCoding#16]
Is there a reason why the podspec only allows macOS use? I'd like to be able to incorporate this pod in an iOS project.

**Comment by samdeane** [comment]
None at all!

Should be fixed by #14.

**Comment by bbeaudry** [comment]
It doesn't seem to be fix. 

> [!] The platform of the target `X` (iOS 10.0) is not compatible with `DictionaryCoding (1.0.3)`, which does not support `ios`.

**Comment by samdeane** [comment]
Ah - might need a new release. Will take a look.

**Comment by samdeane** [comment]
Ok, try release 1.0.4.

**Comment by bbeaudry** [comment]
Ok thanks! I see that you released 1.0.4, but I'm using CocoaPods and the version is still 1.0.3. Is there something you could do?

**Comment by samdeane** [comment]
Oh, damn, didn't realise that there was a version number in the podspec file too. Will fix...

**Comment by bbeaudry** [comment]
Looks great. It would now only need a release of 1.0.5!

**Comment by samdeane** [comment]
Yep - was just waiting for the tests to pass... :)

**Comment by bbeaudry** [comment]
Perfect, thank you so much! Do you have any idea why 1.0.3 is still used on CocoaPods repo - even after a `pod repo update`?

**Comment by samdeane** [comment]
Ah, I need to push the pod to the trunk with `pod trunk push DictionaryCoding.podspec` I think.

Unfortunately I can't do it right now as I'm getting a warning from cocoa pods, which seems to be related to CocoaPods/CocoaPods#8287.

I think I need to wait for that fix to hit the released version of cocoapods.

**Comment by samdeane** [comment]
Ok, figured it out. Try version 1.0.6, which should hopefully be on the CocoaPods repo too.

**Comment by bbeaudry** [comment]
Works like a charm. Thank you so much!
