### ISSUE TITLE
Minimum deployment target for iOS

### ISSUE THREAD

**Issue by igorkulman** [elegantchaos/DictionaryCoding#17]
I have added the library to my iOS project using Carthage, but Xcode says

````
Module file's minimum deployment target is ios11.4 v11.4
````

Is there a reason for that? The code looks like it should build and work also with older versions (my minimum is 10.0).

**Comment by drkibitz** [comment]
Same here.

**Comment by samdeane** [comment]
I don't think there should be a problem. The Cocoa Pods podspec specifies ios10 as the deployment target.

There's no explicit Cartfile for Carthage, so I'm not sure where that minimum is coming from. Probably just from the Xcode project/target, which I generated automatically using `swift package generate-xcodeproj`.

I can probably fix that by getting it to use an `xcconfig` file and setting the mimum there.

**Comment by samdeane** [comment]
(I don't generally use CocoaPods or Carthage so I'm a bit sketchy on the details :) )

**Comment by igorkulman** [comment]
It comes from the Xcode project.

**Comment by drkibitz** [comment]
The xcode project is committed, so anything that would generate that setting doesn't apply.

**Comment by CutFlame** [comment]
fixed with PR #19 
if you want to test put this in your Cartfile:
`github "CutFlame/DictionaryCoding" "issue/17-carthage-ios-support"`

should build with minimum deployment target iOS 10.0

**Comment by samdeane** [comment]
Should be fixed in 1.0.6 - see comment history of #16.
